//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface ICalculoCdbClient {
    calculoCdb_CalcularCdb(request: RequisicaoInvestimentoDto): Observable<ResultadoInvestimentoDto>;
}

@Injectable({
    providedIn: 'root'
})
export class CalculoCdbClient implements ICalculoCdbClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    calculoCdb_CalcularCdb(request: RequisicaoInvestimentoDto): Observable<ResultadoInvestimentoDto> {
        let url_ = this.baseUrl + "/api/CalculoCdb/calcular-cdb";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCalculoCdb_CalcularCdb(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCalculoCdb_CalcularCdb(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ResultadoInvestimentoDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ResultadoInvestimentoDto>;
        }));
    }

    protected processCalculoCdb_CalcularCdb(response: HttpResponseBase): Observable<ResultadoInvestimentoDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoInvestimentoDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class ResultadoInvestimentoDto implements IResultadoInvestimentoDto {
    resultadoBruto?: number;
    resultadoLiquido?: number;
    rendimentoTotal?: number;
    impostoRenda?: number;

    constructor(data?: IResultadoInvestimentoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.resultadoBruto = _data["resultadoBruto"];
            this.resultadoLiquido = _data["resultadoLiquido"];
            this.rendimentoTotal = _data["rendimentoTotal"];
            this.impostoRenda = _data["impostoRenda"];
        }
    }

    static fromJS(data: any): ResultadoInvestimentoDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoInvestimentoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["resultadoBruto"] = this.resultadoBruto;
        data["resultadoLiquido"] = this.resultadoLiquido;
        data["rendimentoTotal"] = this.rendimentoTotal;
        data["impostoRenda"] = this.impostoRenda;
        return data;
    }
}

export interface IResultadoInvestimentoDto {
    resultadoBruto?: number;
    resultadoLiquido?: number;
    rendimentoTotal?: number;
    impostoRenda?: number;
}

export class RequisicaoInvestimentoDto implements IRequisicaoInvestimentoDto {
    valorInicial?: number;
    duracaoEmMeses?: number;

    constructor(data?: IRequisicaoInvestimentoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.valorInicial = _data["valorInicial"];
            this.duracaoEmMeses = _data["duracaoEmMeses"];
        }
    }

    static fromJS(data: any): RequisicaoInvestimentoDto {
        data = typeof data === 'object' ? data : {};
        let result = new RequisicaoInvestimentoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["valorInicial"] = this.valorInicial;
        data["duracaoEmMeses"] = this.duracaoEmMeses;
        return data;
    }
}

export interface IRequisicaoInvestimentoDto {
    valorInicial?: number;
    duracaoEmMeses?: number;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}